# Generated by Django 4.2.1 on 2023-05-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=45, verbose_name='Город')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
    ]
