# Generated by Django 4.2.1 on 2023-05-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Город')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
    ]
