# Generated by Django 4.2.1 on 2023-05-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clientcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('photo', models.CharField(max_length=450, verbose_name='Фото')),
                ('quantity', models.IntegerField(verbose_name='Колличество')),
                ('flag', models.IntegerField(verbose_name='Флаг')),
            ],
        ),
    ]
